//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Packages/com.dragyngames.dgconsole/Runtime/ConsoleAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Packages/com.dragyngames.dgconsole/Runtime/ConsoleAction.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @ConsoleAction: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @ConsoleAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""ConsoleAction"",
    ""maps"": [
        {
            ""name"": ""ConsoleVisibility"",
            ""id"": ""cde1e926-e607-4daa-bc64-e5cad033603b"",
            ""actions"": [
                {
                    ""name"": ""ToggleWindow"",
                    ""type"": ""Button"",
                    ""id"": ""8c1933d9-75f8-476e-827d-655aa504ea3b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f22b25c9-f00f-4e36-8ffb-0db1d52f7142"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleWindow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ConsoleControls"",
            ""id"": ""b634ea70-3bd1-4a99-9f9d-a8c603f5e429"",
            ""actions"": [
                {
                    ""name"": ""CycleHistoryUp"",
                    ""type"": ""Button"",
                    ""id"": ""f4de4004-1fc5-4f4e-9537-6a2017cdf7a8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CycleHistoryDown"",
                    ""type"": ""Button"",
                    ""id"": ""6c2259ff-adb7-4a8e-add3-f38f080ce2f2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CycleSuggestionsUp"",
                    ""type"": ""Button"",
                    ""id"": ""525c24ce-9e40-4818-a893-fd4238011d29"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CycleSuggestionsDown"",
                    ""type"": ""Button"",
                    ""id"": ""2ae9658d-01bc-4502-b2da-3fb26d06d4c8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""64b2dc56-ad74-4d1e-ad07-a90f54d99568"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CycleHistoryUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9daf7f4-e8d5-42b0-a9f1-949536a07323"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CycleHistoryDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""62c8972d-188c-4010-b361-24d52af59447"",
                    ""path"": ""OneModifier(modifiersOrder=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CycleSuggestionsUp"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""6455057e-a9e6-4edf-8234-0c4a8a6fcfe2"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CycleSuggestionsUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""a33f9b96-7160-46aa-a026-b60bff5487a9"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CycleSuggestionsUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""7a59eba6-4d70-4b41-afeb-d9214c4dd87f"",
                    ""path"": ""OneModifier(modifiersOrder=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CycleSuggestionsDown"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""781aebc5-e2de-45da-8b8c-83eaed0184ce"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CycleSuggestionsDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""0648b43c-24a5-4368-9df2-1f20d583c997"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CycleSuggestionsDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ConsoleVisibility
        m_ConsoleVisibility = asset.FindActionMap("ConsoleVisibility", throwIfNotFound: true);
        m_ConsoleVisibility_ToggleWindow = m_ConsoleVisibility.FindAction("ToggleWindow", throwIfNotFound: true);
        // ConsoleControls
        m_ConsoleControls = asset.FindActionMap("ConsoleControls", throwIfNotFound: true);
        m_ConsoleControls_CycleHistoryUp = m_ConsoleControls.FindAction("CycleHistoryUp", throwIfNotFound: true);
        m_ConsoleControls_CycleHistoryDown = m_ConsoleControls.FindAction("CycleHistoryDown", throwIfNotFound: true);
        m_ConsoleControls_CycleSuggestionsUp = m_ConsoleControls.FindAction("CycleSuggestionsUp", throwIfNotFound: true);
        m_ConsoleControls_CycleSuggestionsDown = m_ConsoleControls.FindAction("CycleSuggestionsDown", throwIfNotFound: true);
    }

    ~@ConsoleAction()
    {
        UnityEngine.Debug.Assert(!m_ConsoleVisibility.enabled, "This will cause a leak and performance issues, ConsoleAction.ConsoleVisibility.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_ConsoleControls.enabled, "This will cause a leak and performance issues, ConsoleAction.ConsoleControls.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ConsoleVisibility
    private readonly InputActionMap m_ConsoleVisibility;
    private List<IConsoleVisibilityActions> m_ConsoleVisibilityActionsCallbackInterfaces = new List<IConsoleVisibilityActions>();
    private readonly InputAction m_ConsoleVisibility_ToggleWindow;
    /// <summary>
    /// Provides access to input actions defined in input action map "ConsoleVisibility".
    /// </summary>
    public struct ConsoleVisibilityActions
    {
        private @ConsoleAction m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public ConsoleVisibilityActions(@ConsoleAction wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "ConsoleVisibility/ToggleWindow".
        /// </summary>
        public InputAction @ToggleWindow => m_Wrapper.m_ConsoleVisibility_ToggleWindow;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_ConsoleVisibility; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="ConsoleVisibilityActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(ConsoleVisibilityActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="ConsoleVisibilityActions" />
        public void AddCallbacks(IConsoleVisibilityActions instance)
        {
            if (instance == null || m_Wrapper.m_ConsoleVisibilityActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ConsoleVisibilityActionsCallbackInterfaces.Add(instance);
            @ToggleWindow.started += instance.OnToggleWindow;
            @ToggleWindow.performed += instance.OnToggleWindow;
            @ToggleWindow.canceled += instance.OnToggleWindow;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="ConsoleVisibilityActions" />
        private void UnregisterCallbacks(IConsoleVisibilityActions instance)
        {
            @ToggleWindow.started -= instance.OnToggleWindow;
            @ToggleWindow.performed -= instance.OnToggleWindow;
            @ToggleWindow.canceled -= instance.OnToggleWindow;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="ConsoleVisibilityActions.UnregisterCallbacks(IConsoleVisibilityActions)" />.
        /// </summary>
        /// <seealso cref="ConsoleVisibilityActions.UnregisterCallbacks(IConsoleVisibilityActions)" />
        public void RemoveCallbacks(IConsoleVisibilityActions instance)
        {
            if (m_Wrapper.m_ConsoleVisibilityActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="ConsoleVisibilityActions.AddCallbacks(IConsoleVisibilityActions)" />
        /// <seealso cref="ConsoleVisibilityActions.RemoveCallbacks(IConsoleVisibilityActions)" />
        /// <seealso cref="ConsoleVisibilityActions.UnregisterCallbacks(IConsoleVisibilityActions)" />
        public void SetCallbacks(IConsoleVisibilityActions instance)
        {
            foreach (var item in m_Wrapper.m_ConsoleVisibilityActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ConsoleVisibilityActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="ConsoleVisibilityActions" /> instance referencing this action map.
    /// </summary>
    public ConsoleVisibilityActions @ConsoleVisibility => new ConsoleVisibilityActions(this);

    // ConsoleControls
    private readonly InputActionMap m_ConsoleControls;
    private List<IConsoleControlsActions> m_ConsoleControlsActionsCallbackInterfaces = new List<IConsoleControlsActions>();
    private readonly InputAction m_ConsoleControls_CycleHistoryUp;
    private readonly InputAction m_ConsoleControls_CycleHistoryDown;
    private readonly InputAction m_ConsoleControls_CycleSuggestionsUp;
    private readonly InputAction m_ConsoleControls_CycleSuggestionsDown;
    /// <summary>
    /// Provides access to input actions defined in input action map "ConsoleControls".
    /// </summary>
    public struct ConsoleControlsActions
    {
        private @ConsoleAction m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public ConsoleControlsActions(@ConsoleAction wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "ConsoleControls/CycleHistoryUp".
        /// </summary>
        public InputAction @CycleHistoryUp => m_Wrapper.m_ConsoleControls_CycleHistoryUp;
        /// <summary>
        /// Provides access to the underlying input action "ConsoleControls/CycleHistoryDown".
        /// </summary>
        public InputAction @CycleHistoryDown => m_Wrapper.m_ConsoleControls_CycleHistoryDown;
        /// <summary>
        /// Provides access to the underlying input action "ConsoleControls/CycleSuggestionsUp".
        /// </summary>
        public InputAction @CycleSuggestionsUp => m_Wrapper.m_ConsoleControls_CycleSuggestionsUp;
        /// <summary>
        /// Provides access to the underlying input action "ConsoleControls/CycleSuggestionsDown".
        /// </summary>
        public InputAction @CycleSuggestionsDown => m_Wrapper.m_ConsoleControls_CycleSuggestionsDown;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_ConsoleControls; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="ConsoleControlsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(ConsoleControlsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="ConsoleControlsActions" />
        public void AddCallbacks(IConsoleControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_ConsoleControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ConsoleControlsActionsCallbackInterfaces.Add(instance);
            @CycleHistoryUp.started += instance.OnCycleHistoryUp;
            @CycleHistoryUp.performed += instance.OnCycleHistoryUp;
            @CycleHistoryUp.canceled += instance.OnCycleHistoryUp;
            @CycleHistoryDown.started += instance.OnCycleHistoryDown;
            @CycleHistoryDown.performed += instance.OnCycleHistoryDown;
            @CycleHistoryDown.canceled += instance.OnCycleHistoryDown;
            @CycleSuggestionsUp.started += instance.OnCycleSuggestionsUp;
            @CycleSuggestionsUp.performed += instance.OnCycleSuggestionsUp;
            @CycleSuggestionsUp.canceled += instance.OnCycleSuggestionsUp;
            @CycleSuggestionsDown.started += instance.OnCycleSuggestionsDown;
            @CycleSuggestionsDown.performed += instance.OnCycleSuggestionsDown;
            @CycleSuggestionsDown.canceled += instance.OnCycleSuggestionsDown;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="ConsoleControlsActions" />
        private void UnregisterCallbacks(IConsoleControlsActions instance)
        {
            @CycleHistoryUp.started -= instance.OnCycleHistoryUp;
            @CycleHistoryUp.performed -= instance.OnCycleHistoryUp;
            @CycleHistoryUp.canceled -= instance.OnCycleHistoryUp;
            @CycleHistoryDown.started -= instance.OnCycleHistoryDown;
            @CycleHistoryDown.performed -= instance.OnCycleHistoryDown;
            @CycleHistoryDown.canceled -= instance.OnCycleHistoryDown;
            @CycleSuggestionsUp.started -= instance.OnCycleSuggestionsUp;
            @CycleSuggestionsUp.performed -= instance.OnCycleSuggestionsUp;
            @CycleSuggestionsUp.canceled -= instance.OnCycleSuggestionsUp;
            @CycleSuggestionsDown.started -= instance.OnCycleSuggestionsDown;
            @CycleSuggestionsDown.performed -= instance.OnCycleSuggestionsDown;
            @CycleSuggestionsDown.canceled -= instance.OnCycleSuggestionsDown;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="ConsoleControlsActions.UnregisterCallbacks(IConsoleControlsActions)" />.
        /// </summary>
        /// <seealso cref="ConsoleControlsActions.UnregisterCallbacks(IConsoleControlsActions)" />
        public void RemoveCallbacks(IConsoleControlsActions instance)
        {
            if (m_Wrapper.m_ConsoleControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="ConsoleControlsActions.AddCallbacks(IConsoleControlsActions)" />
        /// <seealso cref="ConsoleControlsActions.RemoveCallbacks(IConsoleControlsActions)" />
        /// <seealso cref="ConsoleControlsActions.UnregisterCallbacks(IConsoleControlsActions)" />
        public void SetCallbacks(IConsoleControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_ConsoleControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ConsoleControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="ConsoleControlsActions" /> instance referencing this action map.
    /// </summary>
    public ConsoleControlsActions @ConsoleControls => new ConsoleControlsActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "ConsoleVisibility" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="ConsoleVisibilityActions.AddCallbacks(IConsoleVisibilityActions)" />
    /// <seealso cref="ConsoleVisibilityActions.RemoveCallbacks(IConsoleVisibilityActions)" />
    public interface IConsoleVisibilityActions
    {
        /// <summary>
        /// Method invoked when associated input action "ToggleWindow" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnToggleWindow(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "ConsoleControls" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="ConsoleControlsActions.AddCallbacks(IConsoleControlsActions)" />
    /// <seealso cref="ConsoleControlsActions.RemoveCallbacks(IConsoleControlsActions)" />
    public interface IConsoleControlsActions
    {
        /// <summary>
        /// Method invoked when associated input action "CycleHistoryUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCycleHistoryUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CycleHistoryDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCycleHistoryDown(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CycleSuggestionsUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCycleSuggestionsUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CycleSuggestionsDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCycleSuggestionsDown(InputAction.CallbackContext context);
    }
}
